### ISSUE TITLE
快点更新谢谢

### ISSUE THREAD

**Issue by woshigerunze** [CnNullptr/LearnAndroid#1]

**Comment by CnNullptr** [comment]
等着挂科吧你

**Comment by woshigerunze** [comment]
我操你妈




------------------ 原始邮件 ------------------
发件人: nullptr <notifications@github.com>
发送时间: 2019年4月13日 14:43
收件人: CnNullptr/LearnAndroid <LearnAndroid@noreply.github.com>
抄送: 葛润泽 <664279928@qq.com>, Author <author@noreply.github.com>
主题: 回复：[CnNullptr/LearnAndroid] 快点更新谢谢 (#1)
